CREATE TABLE AUDITLOG_TB
( ID NUMBER(20,0) NOT NULL,
  OBJ_TYPE VARCHAR2(100) ,
  OBJ_ID NUMBER(20,0),
  TRANSACTION_TYPE VARCHAR2(10),
  OLD_VALUE VARCHAR2(200),
  NEW_VALUE VARCHAR2(200),
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT AUDITLOG_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE AUDITLOG_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;

ALTER TABLE AUDITLOG_TB MODIFY NEW_VALUE VARCHAR2(1000);
commit;

ALTER TABLE AUDITLOG_TB MODIFY OLD_VALUE VARCHAR2(1000);
commit;