CREATE TABLE AUDITLOG_TB
( ID NUMBER(20,0) NOT NULL,
  OBJ_TYPE VARCHAR2(100) ,
  OBJ_ID NUMBER(20,0),
  TRANSACTION_TYPE VARCHAR2(10),
  OLD_VALUE VARCHAR2(200),
  NEW_VALUE VARCHAR2(200),
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT AUDITLOG_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE AUDITLOG_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;



CREATE TABLE ACTIVITY_LOG_TB
( ACTIVITYLOGID NUMBER(20,0) NOT NULL,
  ACTION VARCHAR2(100) ,
  CONTROLLER VARCHAR2(100),
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT ACTIVITY_LOG_PK PRIMARY KEY (ACTIVITYLOGID)
);

CREATE SEQUENCE ACTIVITY_LOG_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;

CREATE TABLE MASTER_CODETYPE_TB
( MASTERCODETYPEID NUMBER(20,0) NOT NULL,
  CODE VARCHAR2(150) ,
  NAME VARCHAR2(150),
  SORTORDER NUMBER(6,0) NOT NULL,
  VERSION NUMBER(6,0) NOT NULL,
  EFFECTIVEDATE TIMESTAMP,
  EXPIRYDATE TIMESTAMP,
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT MASTER_CODETYPE_PK PRIMARY KEY (MASTERCODETYPEID)
);

CREATE SEQUENCE MASTER_CODETYPE_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;

CREATE TABLE MASTER_CODEVALUE_TB
( MASTERCODEID NUMBER(20,0) NOT NULL,
  DESCRIPTION VARCHAR2(250) NOT NULL,
  REMARKS VARCHAR2(150),
  CODEVALUE VARCHAR2(200) NOT NULL,
  SEQUENCENO NUMBER(6,0) ,
  MASTERCODETYPEID NUMBER(20,0) NOT NULL,
  EFFECTIVEDATE TIMESTAMP,
  EXPIRYDATE TIMESTAMP,
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT MASTER_CODEVALUE_PK PRIMARY KEY (MASTERCODEID)
);

CREATE SEQUENCE MASTER_CODEVALUE_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;




