
CREATE TABLE ACCOUNT_TB (
  ACCOUNTID	BIGINT	NOT NULL,
  ACCT_CODE	VARCHAR(100) NOT NULL,
  ACCT_DESC	VARCHAR(400) NOT NULL,
  REQ_FORM	CHARACTER(1)	NOT NULL,
  SPEND_PRD SMALLINT NOT NULL,
  FY VARCHAR(20) NOT NULL,
  MODIFIEDBY	BIGINT,
  DATEMODIFIED	TIMESTAMP,
  CREATEDBY	BIGINT	NOT NULL,
  DATECREATED	TIMESTAMP	NOT NULL,
  ACTIVE_IND	CHARACTER(1)	NOT NULL,
  CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNTID)
  ) 

CREATE SEQUENCE ACCOUNT_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCYCLE
 CACHE 20 ;