CREATE TABLE ACCT_STRUCTURE_TB (
  ACCT_STRUCTURE_ID	BIGINT	NOT NULL,
  ACCOUNTID	BIGINT NOT NULL,
  COLUMN_NAME	VARCHAR(400) NOT NULL,
  COLUMN_SIZE SMALLINT NOT NULL,
  COLUMN_TYPE	CHARACTER(1) NOT NULL,
  SEQUENCE SMALLINT NOT NULL,
  DEFAULT_COL CHAR(1) NOT NULL,
  MODIFIEDBY	BIGINT,
  DATEMODIFIED	TIMESTAMP,
  CREATEDBY	BIGINT	NOT NULL,
  DATECREATED	TIMESTAMP	NOT NULL,
  ACTIVE_IND	CHARACTER(1)	NOT NULL,
  CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCT_STRUCTURE_ID)
  ); 

CREATE SEQUENCE ACCT_STRUCTURE_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCYCLE
 CACHE 20 ;
 
 
 --ALTER TABLE ACCT_STRUCTURE_TB ADD DEFAULT_COL CHAR(1) DEFAULT 'N' NOT NULL;