CREATE TABLE ACTIVITY_LOG_TB
( ACTIVITYLOGID NUMBER(20,0) NOT NULL,
  ACTION VARCHAR2(100) ,
  CONTROLLER VARCHAR2(100),
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT ACTIVITY_LOG_PK PRIMARY KEY (ACTIVITYLOGID)
);

CREATE SEQUENCE ACTIVITY_LOG_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;