CREATE TABLE BUDGET_CONFIG_TB
( BUDGETCONFIGID BIGINT NOT NULL,
  BUDGETCONFIGFY SMALLINT NOT NULL,
  BUDGETING_START_DT TIMESTAMP NOT NULL,
  BUDGETING_END_DT TIMESTAMP NOT NULL,
  WORKING_BUDGET_START_DT TIMESTAMP,
  WORKING_BUDGET_END_DT TIMESTAMP,
  BUDGETSNAPSHOTID BIGINT ,
  MODIFIEDBY BIGINT ,
  DATEMODIFIED TIMESTAMP,
  CREATEDBY BIGINT  NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT BUDGET_CONFIG_PK PRIMARY KEY (BUDGETCONFIGID)
);

CREATE SEQUENCE BUDGET_CONFIG_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCYCLE
 CACHE 20 ;

COMMIT;