CREATE TABLE MASTER_CODETYPE_TB
( MASTERCODETYPEID NUMBER(20,0) NOT NULL,
  CODE VARCHAR2(150) ,
  NAME VARCHAR2(150),
  SORTORDER NUMBER(6,0) NOT NULL,
  VERSION NUMBER(6,0) NOT NULL,
  EFFECTIVEDATE TIMESTAMP,
  EXPIRYDATE TIMESTAMP,
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT MASTER_CODETYPE_PK PRIMARY KEY (MASTERCODETYPEID)
);

CREATE SEQUENCE MASTER_CODETYPE_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;