CREATE TABLE MASTER_CODEVALUE_TB
( MASTERCODEID NUMBER(20,0) NOT NULL,
  DESCRIPTION VARCHAR2(250) NOT NULL,
  REMARKS VARCHAR2(150),
  CODEVALUE VARCHAR2(200) NOT NULL,
  SEQUENCENO NUMBER(6,0) ,
  MASTERCODETYPEID NUMBER(20,0) NOT NULL,
  EFFECTIVEDATE TIMESTAMP,
  EXPIRYDATE TIMESTAMP,
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT MASTER_CODEVALUE_PK PRIMARY KEY (MASTERCODEID)
);

CREATE SEQUENCE MASTER_CODEVALUE_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;
