CREATE TABLE SECURITY_QUESTION_TB
( SECURITYQUESTIONID NUMBER(20,0) NOT NULL,
  QUESTION VARCHAR2(500) ,
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT SECURITY_QUESTION_PK PRIMARY KEY (SECURITYQUESTIONID)
);

CREATE SEQUENCE SECURITY_QUESTION_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;