CREATE TABLE USER_TB
( USERID NUMBER(20,0) NOT NULL,
  NAME VARCHAR2(150) NOT NULL,
  LOGINID VARCHAR2(150) NOT NULL,
  PASSWORD VARCHAR2(150),
  SALUTATION NUMBER(20,0) NOT NULL,
  STATUS VARCHAR2(20) NOT NULL,
  GENDER NUMBER(20,0) ,
  DATEOFBIRTH TIMESTAMP,
  OFFICETEL VARCHAR2(20),
  MOBILENUM VARCHAR2(20),
  PREFERREDCONTACTMODE VARCHAR2(50),
  PASSWORDLASTUPDATEDATE TIMESTAMP,
  LASTSUCCESSLOGINDATE TIMESTAMP,
  LASTFAILEDLOGINDATE TIMESTAMP,
  MODIFIEDBY NUMBER(20,0),
  DATEMODIFIED TIMESTAMP,
  CREATEDBY NUMBER(20,0) NOT NULL,
  DATECREATED TIMESTAMP NOT NULL,
  ACTIVE_IND CHAR(1) NOT NULL,
  CONSTRAINT USER_PK PRIMARY KEY (USERID)
);

CREATE SEQUENCE USER_SEQ
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1 
 MAXVALUE 9223372036854775807
 NOCYCLE
 CACHE 20 ;

COMMIT;

ALTER TABLE USER_TB MODIFY PASSWORD VARCHAR2(1000);
commit;