
CREATE TABLE USER_ACCT_MAPPING_TB (
  USER_ACCT_MAPPING_ID	BIGINT	NOT NULL,
  USERID	BIGINT NOT NULL,
  ACCT_CODE	VARCHAR(100) NOT NULL,  
  MODIFIEDBY	BIGINT,
  DATEMODIFIED	TIMESTAMP,
  CREATEDBY	BIGINT	NOT NULL,
  DATECREATED	TIMESTAMP	NOT NULL,
  ACTIVE_IND	CHARACTER(1)	NOT NULL,
  CONSTRAINT ACCOUNT_PK PRIMARY KEY (USER_ACCT_MAPPING_ID)
  ); 

CREATE SEQUENCE USER_ACCT_MAPPING_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCYCLE
 CACHE 20 ;